crime_weights = {
    "Other Assaults": 0.5,
    "Aggravated Assault No Firearm": 0.7,
    "Aggravated Assault Firearm": 1.0,
    "Thefts": 0.7,
    "Weapon Violations": 0.4,
    "All Other Offenses": 0.2,
    "Vandalism/Criminal Mischief": 0.2,
    "Motor Vehicle Theft": 0.7,
    "Robbery No Firearm": 0.6,
    "Theft from Vehicle": 0.4,
    "Narcotic / Drug Law Violations": 0.3,
    "Fraud": 0.1,
    "Arson": 0.3,
    "Embezzlement": 0.1,
    "Burglary Non-Residential": 0.5,
    "Burglary Residential": 0.6,
    "Other Sex Offenses (Not Commercialized)": 0.9,
    "Receiving Stolen Property": 0.3,
    "Robbery Firearm": 1.0,
    "Vagrancy/Loitering": 0.1,
    "Rape": 1.0,
    "Offenses Against Family and Children": 0.8,
    "Disorderly Conduct": 0.2,
    "DRIVING UNDER THE INFLUENCE": 0.6,
    "Prostitution and Commercialized Vice": 0.3,
    "Forgery and Counterfeiting": 0.2,
    "Public Drunkenness": 0.2,
    "Homicide - Criminal": 1.0,
    "Liquor Law Violations": 0.1,
    "Gambling Violations": 0.1,
    "Homicide - Justifiable": 0.1,
    "Homicide - Gross Negligence": 0.6,
}


